package ua.dragunov.watchlyapi.model;

public enum PersonRoleType {
    ACTOR,
    VOICE_ACTOR,
    DIRECTOR,
    PRODUCER,
    EXECUTIVE_PRODUCER,
    WRITER,
    SCREENPLAY,
    COMPOSER,
    CINEMATOGRAPHER,
    EDITOR,
    PRODUCTION_DESIGNER,
    ART_DIRECTOR,
    COSTUME_DESIGNER,
    MAKEUP_ARTIST,
    VISUAL_EFFECTS_SUPERVISOR,
    SOUND_DESIGNER,
    CASTING_DIRECTOR,
    STUNT_COORDINATOR
}
